name: 'dbt_xorq'
version: '1.0.0'
config-version: 2

profile: 'dbt_xorq'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_xorq:
    examples:
      +schema: iceberg_models
